framework:
    workflows:
        beerglass_2_alternative:
            type: state_machine
            marking_store:
                type: single_state
                arguments:
                    - state
            supports:
                - App\Document\BeerGlass
            places:
                - clean
                - filling
                - full
                - drinking
                - dirty
                - washing
            transitions:
                pour:
                    from: clean
                    to: filling
                stop_pouring:
                    from: filling
                    to: full
                drink:
                    from: full
                    to: drinking
                finish:
                    from: [full, drinking]
                    to: dirty
                wash:
                    from: dirty
                    to: washing
                cleaned:
                    from: washing
                    to: clean